// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddNewCertificateModal: typeof import('./components/certificates/AddNewCertificateModal.vue')['default']
    BaseAlert: typeof import('./components/BaseAlert.vue')['default']
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    BaseToggle: typeof import('./components/BaseToggle.vue')['default']
    BusyOverlay: typeof import('./components/BusyOverlay.vue')['default']
    CategorySelect: typeof import('./components/CategorySelect.vue')['default']
    CertificatesList: typeof import('./components/certificates/CertificatesList.vue')['default']
    CertificatesListItem: typeof import('./components/certificates/CertificatesListItem.vue')['default']
    CircleSpinner: typeof import('./components/CircleSpinner.vue')['default']
    DashboardOverview: typeof import('./components/DashboardOverview.vue')['default']
    EmptyCollection: typeof import('./components/EmptyCollection.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
  }
}

export { }
